// Generates every logo variant (SVG + PNG) from the exact geometry of apps/web/public/logo.svg.
// Run from the repo root:  node brand/tools/build-logos.mjs
// Needs Playwright (only for measuring the wordmark and rasterising PNGs); nothing is installed.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const out = join(here, '..', 'assets', 'logo');
const png = join(out, 'png');
mkdirSync(png, { recursive: true });

const require = createRequire('C:/Users/Rofi/Documents/Codes/CatCoder/CatCoder/node_modules/');
const { chromium } = require('playwright');

// ── Brand constants (must match apps/web/public/cc.css and logo.svg) ──
const C = { lime1: '#c8f56e', lime2: '#a3e635', ink: '#14310a', bg: '#0a0b0d', white: '#f7f8f8' };
const fontB64 = readFileSync(join(here, '..', 'assets', 'fonts', 'space-grotesk-latin-wght-normal.woff2')).toString('base64');
const fontFace = `@font-face{font-family:"Space Grotesk Variable";font-weight:300 700;src:url(data:font/woff2;base64,${fontB64}) format("woff2");}`;

// The glyph: a rounded square frame (the tablet / the "o") with a notch cut out of its top-right
// corner and a dot sitting in the notch (the "i" of rofi, the status light, the heartbeat).
const maskId = (p) => `${p}m`;
const glyph = (stroke, p = 'g') => `
  <mask id="${maskId(p)}" maskUnits="userSpaceOnUse" x="0" y="0" width="64" height="64"><rect x="0" y="0" width="64" height="64" fill="#fff"/><circle cx="46" cy="18" r="9.5" fill="#000"/></mask>
  <rect x="16" y="16" width="32" height="32" rx="10" fill="none" stroke="${stroke}" stroke-width="7" mask="url(#${maskId(p)})"/>
  <circle cx="46" cy="18" r="5" fill="${stroke}"/>`;
const grad = `<linearGradient id="lg" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="${C.lime1}"/><stop offset="1" stop-color="${C.lime2}"/></linearGradient>`;
const svg = (vb, body, extra = '') => `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${vb}"${extra}>\n${body}\n</svg>\n`;
const tile = (rx = 16) => `<rect width="64" height="64" rx="${rx}" fill="url(#lg)"/>`;
const GLYPH_VB = '12.5 12.5 39 39'; // tight box of the glyph alone

const files = {};
// 1. Primary mark (identical to apps/web/public/logo.svg)
files['mark.svg'] = svg('0 0 64 64', `<defs>${grad}</defs>${tile()}${glyph(C.ink)}`);
// 2. Flat mark (single lime, for one-colour print and tiny sizes)
files['mark-flat.svg'] = svg('0 0 64 64', `${`<rect width="64" height="64" rx="16" fill="${C.lime2}"/>`}${glyph(C.ink)}`);
// 3. Glyph only, no tile
files['glyph-lime.svg'] = svg(GLYPH_VB, glyph(C.lime2));
files['glyph-ink.svg'] = svg(GLYPH_VB, glyph(C.bg));
files['glyph-white.svg'] = svg(GLYPH_VB, glyph('#ffffff'));
// 4. Mono tiles
files['mark-mono-white.svg'] = svg('0 0 64 64', `<rect width="64" height="64" rx="16" fill="#ffffff"/>${glyph(C.bg)}`);
files['mark-mono-black.svg'] = svg('0 0 64 64', `<rect width="64" height="64" rx="16" fill="${C.bg}"/>${glyph('#ffffff')}`);
// 5. App icon masters (square, full bleed: iOS/Android apply their own mask)
files['app-icon-square.svg'] = svg('0 0 64 64', `<defs>${grad}</defs>${tile(0)}${glyph(C.ink)}`);
files['app-icon-dark.svg'] = svg('0 0 64 64', `<rect width="64" height="64" fill="${C.bg}"/><defs><radialGradient id="rg" cx="0.72" cy="0.12" r="0.9"><stop offset="0" stop-color="#a3e635" stop-opacity="0.22"/><stop offset="1" stop-color="#a3e635" stop-opacity="0"/></radialGradient></defs><rect width="64" height="64" fill="url(#rg)"/>${glyph(C.lime2)}`);

writeFileSync(join(out, 'README.txt'), 'Generated by brand/tools/build-logos.mjs. Do not hand-edit.\n');

const browser = await chromium.launch();
const page = await browser.newPage();

// Measure the wordmark: Space Grotesk 700, letter-spacing -0.02em, exactly as in the app.
await page.setContent(`<style>${fontFace}span{font:700 100px "Space Grotesk Variable";letter-spacing:-0.02em;white-space:pre}</style><span id=t>rofihosted</span>`);
await page.evaluate(() => document.fonts.ready);
const textW100 = await page.evaluate(() => document.getElementById('t').getBoundingClientRect().width);

const wordmark = (x, cy, size, fill) => `<text x="${x}" y="${cy}" dominant-baseline="central" font-family="Space Grotesk Variable, Inter, system-ui, sans-serif" font-weight="700" font-size="${size}" letter-spacing="${(-0.02 * size).toFixed(2)}" fill="${fill}">rofihosted</text>`;
const style = `<style>${fontFace}</style>`;

// Horizontal lockup: mark height M, text size 0.5M, gap 0.3125M (the app uses 32px / ~17px / 10px).
const M = 64, T = M * 0.5, GAP = M * 0.3125, textW = (textW100 / 100) * T;
const hw = Math.ceil(M + GAP + textW + 2);
const hBody = (fill, markBody) => `<defs>${grad}${style}</defs><g>${markBody}</g>${wordmark(M + GAP, 33, T, fill)}`;
files['lockup-horizontal.svg'] = svg(`0 0 ${hw} 64`, hBody(C.white, `${tile()}${glyph(C.ink)}`), ` width="${hw * 4}" height="256"`);
files['lockup-horizontal-on-light.svg'] = svg(`0 0 ${hw} 64`, hBody(C.bg, `${tile()}${glyph(C.ink)}`), ` width="${hw * 4}" height="256"`);
files['wordmark-white.svg'] = svg(`0 0 ${Math.ceil(textW + 2)} ${T * 1.3}`, `<defs>${style}</defs>${wordmark(0, T * 0.65, T, C.white)}`);
files['wordmark-ink.svg'] = svg(`0 0 ${Math.ceil(textW + 2)} ${T * 1.3}`, `<defs>${style}</defs>${wordmark(0, T * 0.65, T, C.bg)}`);
// Stacked lockup: mark 64, text 0.5M below, centred, gap 0.5M.
const sw = Math.ceil(Math.max(M, textW) + 2);
const sTextX = (sw - textW) / 2;
files['lockup-stacked.svg'] = svg(`0 0 ${sw} ${M + 32 + T}`, `<defs>${grad}${style}</defs><g transform="translate(${(sw - M) / 2} 0)">${tile()}${glyph(C.ink)}</g>${wordmark(sTextX, M + 32 + T * 0.45, T, C.white)}`);

for (const [name, content] of Object.entries(files)) writeFileSync(join(out, name), content);

// ── Rasterise ──
async function shot(name, sizeW, sizeH, bg = null) {
  const svgText = readFileSync(join(out, name), 'utf8');
  const uri = 'data:image/svg+xml;base64,' + Buffer.from(svgText).toString('base64');
  await page.setViewportSize({ width: sizeW, height: sizeH });
  await page.setContent(`<style>html,body{margin:0;background:${bg || 'transparent'}}img{display:block;width:${sizeW}px;height:${sizeH}px}</style><img src="${uri}">`);
  await page.evaluate(() => document.querySelector('img').decode());
  await page.screenshot({ path: join(png, name.replace(/\.svg$/, '') + `-${sizeW}.png`), omitBackground: !bg });
}
for (const s of [1024, 512, 192, 64, 32]) await shot('mark.svg', s, s);
await shot('mark-flat.svg', 512, 512);
await shot('glyph-lime.svg', 1024, 1024);
await shot('glyph-white.svg', 1024, 1024);
await shot('glyph-ink.svg', 1024, 1024);
await shot('mark-mono-white.svg', 512, 512);
await shot('mark-mono-black.svg', 512, 512);
await shot('app-icon-square.svg', 1024, 1024);
await shot('app-icon-dark.svg', 1024, 1024);
await shot('lockup-horizontal.svg', hw * 8, 512);
await shot('lockup-horizontal-on-light.svg', hw * 8, 512);
await shot('lockup-stacked.svg', 1200, Math.round((1200 * (M + 32 + T)) / sw));
await shot('wordmark-white.svg', Math.ceil(textW) * 8, Math.round(T * 1.3 * 8));
await shot('wordmark-ink.svg', Math.ceil(textW) * 8, Math.round(T * 1.3 * 8));

await browser.close();

// ── WCAG contrast of every text/background pair we document ──
const lum = (hex) => { const c = hex.replace('#', '').match(/../g).map((h) => parseInt(h, 16) / 255).map((v) => (v <= 0.03928 ? v / 12.92 : ((v + 0.055) / 1.055) ** 2.4)); return 0.2126 * c[0] + 0.7152 * c[1] + 0.0722 * c[2]; };
const ratio = (a, b) => { const [x, y] = [lum(a), lum(b)].sort((p, q) => q - p); return +((x + 0.05) / (y + 0.05)).toFixed(2); };
const pairs = [
  ['tx-1 on bg', '#f7f8f8', '#0a0b0d'], ['tx-2 on bg', '#a0a4ad', '#0a0b0d'], ['tx-3 on bg', '#686d77', '#0a0b0d'],
  ['tx-2 on surface-2', '#a0a4ad', '#181a1e'], ['tx-3 on surface-2', '#686d77', '#181a1e'], ['tx-1 on surface-3', '#f7f8f8', '#202329'],
  ['brand-1 on bg', '#bef264', '#0a0b0d'], ['brand-2 on bg', '#a3e635', '#0a0b0d'], ['brand-1 on surface-2', '#bef264', '#181a1e'],
  ['ink on brand-2 (button)', '#14310a', '#a3e635'], ['ink on brand-1', '#14310a', '#c8f56e'],
  ['ac on bg', '#4ade80', '#0a0b0d'], ['wa on bg', '#fb7185', '#0a0b0d'], ['tle on bg', '#fbbf24', '#0a0b0d'], ['info on bg', '#60a5fa', '#0a0b0d'],
  ['bg on tx-1 (set-primary button)', '#0a0b0d', '#f7f8f8'],
];
const table = pairs.map(([n, f, b]) => ({ pair: n, fg: f, bg: b, ratio: ratio(f, b) }));
writeFileSync(join(here, '..', 'tokens', 'contrast.json'), JSON.stringify(table, null, 2) + '\n');
console.log('wordmark width @100px:', textW100.toFixed(1));
console.table(table);
console.log('done:', Object.keys(files).length, 'svg files');
